# Generated by Django 4.2.7 on 2025-10-25 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('استفسار عن منتج', 'استفسار عن منتج'), ('طلب عرض سعر', 'طلب عرض سعر'), ('دعم فني', 'دعم فني'), ('شكوى أو اقتراح', 'شكوى أو اقتراح'), ('أخرى', 'أخرى')], max_length=100, verbose_name='الموضوع'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
    ]
