# Generated by Django 4.2.7 on 2025-10-24 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='offerproduct',
            unique_together={('offer', 'product')},
        ),
    ]
